# Unique name for this workflow
name: Validate PR on integration branch

# Definition when the workflow should run
on:
    pull_request:
        # This workflow will run when a pull request is opened, or when a commit is pushed
        # to a branch that has an existing pull request
        types: [opened, synchronize]
        branches: [ development ]
        # We only care about changes to the force-app directory. This prevents the job from running.
        # when changing non-salesforce files (like this yml file)
        paths:
            - 'force-app/**'

# Jobs to be executed
jobs:
    validate-deployment-on-integration-org:
        runs-on: ubuntu-latest
        if: ${{ github.actor != 'dependabot[bot]'}}
        steps:
            # Install node.js
            - uses: actions/setup-node@v4
              with:
                node-version: '22'
                cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
               